# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Deployment Github Action

on:
  workflow_dispatch:
  push:
    branches: [ "test-ci", "master" ]

jobs:
  Check-Angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            angular-chat/package-lock.json
      - name: Install
        run: npm ci
        working-directory: angular-chat
      - name: Build
        run: npm run build
        working-directory: angular-chat
      - name: Test karma
        run: npm run test:prod
        working-directory: angular-chat
      - name: Test Cypress
        run: npm run test:cypress
        working-directory: angular-chat
  Check-React:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            react-chat/package-lock.json
      - name: Install
        run: npm ci
        working-directory: react-chat
      - name: Build
        run: npm run build
        working-directory: react-chat
  Check-Vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            vue-chat/package-lock.json
      - name: Install
        run: npm ci
        working-directory: vue-chat
      - name: Build
        run: npm run build
        working-directory: vue-chat
      - name: Test
        run: npm run test:unit
        working-directory: vue-chat
  Run-E2E:
    needs: [ Check-Vue,Check-Angular,Check-React ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            vue-chat/package-lock.json
            react-chat/package-lock.json
            angular-chat/package-lock.json
      - name: Use Java
        uses: actions/setup-java@v3
        with:
          cache: 'maven'
          java-version: '17'
      - name: Start Angular
        run: |
          cd angular-chat &&
          npm ci && 
          npm run start &
          sleep 5
      - name: Start React
        run: |
          cd react-chat &&
          npm ci && 
          npm run dev &
          sleep 5
      - name: Start React
        run: |
          cd vue-chat &&
          npm ci && 
          npm run dev  &
          sleep 5
      - name: Run docker-compose
        run: |
          cd deploy && 
          docker compose -f docker-compose.yml up -d
      - name: Install mvn packages
        run: |
          cd chat-api
          mvn compile
      - name: Start backend
        run: |
          cd chat-api
          mvn spring-boot:run  &
          sleep 5
      - name: Install and run cypress
        run: |
          cd e2e-tests
          npm ci
          npm run start
    

